print("¡Generemos un conflicto en esta linea!")


print("*********** Profes ***********")
print("Alicia, Omar, Lucía                      -----> Omar re estuvo aqui")

print("\n*********** Alumnos ***********")
print("Acuña, German Federico                   -----> ESCRIBIR AQUI")
print("Adamo Morales, Federico Ignacio          -----> ESCRIBIR AQUI")
print("Alegre, Franco                           -----> ESCRIBIR AQUI")
print("Alegre Vegas, Gonzalo Manuel             -----> ESCRIBIR AQUI")
print("Almirón, Victoria Carolina               -----> ESCRIBIR AQUI")
print("Amarillo, Elisa Maribel                  -----> ESCRIBIR AQUI")
print("Andrada, Silvana Raquel                  -----> ESCRIBIR AQUI")
print("Azpiroz, Alejo Hernan                    -----> ESCRIBIR AQUI")
print("Barrionuevo, Paulo                       -----> ESCRIBIR AQUI")
print("Benz, Damian Agustin                     -----> ESCRIBIR AQUI")
print("Blanco, Nahuel                           -----> Buenaaaaaaass")
print("Bonanno, Franco Miguel                   -----> ESCRIBIR AQUI")
print("Bonino, Amarú Jesus                      -----> ESCRIBIR AQUI")
print("Bulacio, Lucia                           -----> ESCRIBIR AQUI")
print("Callero, Micaela Cecilia                 -----> ESCRIBIR AQUI")
print("Carrica, Leandro Dario                   -----> ESCRIBIR AQUI")
print("Castro Pariona, Matias                   -----> ESCRIBIR AQUI")
print("Cavagnero, Nahún Joaquín                 -----> ESCRIBIR AQUI")
print("Chianese, Braian Nahuel                  -----> ESCRIBIR AQUI")
print("Cisneros, Lucas Damian                   -----> ESCRIBIR AQUI")
print("Colombo, Agustina                        -----> ESCRIBIR AQUI")
print("Cordua, Kevin Nicolas Daniel             -----> ESCRIBIR AQUI")
print("Cornu Baroni, Elias Leonel               -----> ESCRIBIR AQUI")
print("Corvalan, Lautaro Juan Cruz              -----> ESCRIBIR AQUI")
print("Cruceño, Ricardo Gabriel                 -----> ESCRIBIR AQUI")
print("Diaz, Ornella                            -----> ESCRIBIR AQUI")
print("Diaz, Stefano Santino                    -----> ESCRIBIR AQUI")
print("Ducca, Iván Tomás                        -----> ESCRIBIR AQUI")
print("Escobar, Pedro Alessandro                -----> ESCRIBIR AQUI")
print("Falcon, Aldana Abigail                   -----> ESCRIBIR AQUI")
print("Farias Medina, Alexis Gabriel            -----> ESCRIBIR AQUI")
print("Fernandez, Gonzalo Roman                 -----> ESCRIBIR AQUI")
print("Flores, Elian Genaro                     -----> ESCRIBIR AQUI")
print("Fonseca, Ulises                          -----> ESCRIBIR AQUI")
print("Franco, Jacqueline                       -----> ESCRIBIR AQUI")
print("Galindez, Esteban                        -----> ESCRIBIR AQUI")
print("Gomez, Maira Agustina                    -----> ESCRIBIR AQUI")
print("Gomez Roa, Iara Candela                  -----> ESCRIBIR AQUI")
print("Gomez, Santiago Daniel                   -----> ESCRIBIR AQUI")
print("Gomez Segovia, Tiago Andres              -----> ESCRIBIR AQUI")
print("Gorosito, Gonzalo                        -----> ESCRIBIR AQUI")
print("Herrera Fernández, Franco Nicolás        -----> ESCRIBIR AQUI")
print("Ibarra Flores, Facundo Ariel             -----> ESCRIBIR AQUI")
print("Juarez, Lucas Gaston                     -----> ESCRIBIR AQUI")
print("Lago, Santiago                           -----> ESCRIBIR AQUI")
print("Lavallós, Elian Nahuel                   -----> ESCRIBIR AQUI")
print("Lazarte, Facundo                         -----> Modifico esta linea")
print("Lopez Carro, Nicolas Enrique             -----> ESCRIBIR AQUI")
print("Ledesma, Tomás Alejo                     -----> ESCRIBIR AQUI")
print("Lividisky, Iván Vladimir Ariel           -----> ESCRIBIR AQUI")
print("Maldonado, Luciano Agustín               -----> ESCRIBIR AQUI")
print("Maldonado, Tomas Agustin                 -----> ESCRIBIR AQUI")
print("Malgarini, Bautista Gabriel              -----> ESCRIBIR AQUI")
print("Minet, Agustín Elias                     -----> ESCRIBIR AQUI")
print("Nieto Robledo, Emanuel                   -----> ESCRIBIR AQUI")
print("Olmos, Yanina Belen                      -----> ESCRIBIR AQUI")
print("Ortiz, Alejandro Ezequiel                -----> ESCRIBIR AQUI")
print("Paez, Ariana                             -----> ESCRIBIR AQUI")
print("Paredes, Ariel Alejandro                 -----> ESCRIBIR AQUI")
print("Paredes, Ignacio Alcides                 -----> ESCRIBIR AQUI")
print("Paz, Walter Ricardo                      -----> ESCRIBIR AQUI")
print("Perkal, Ezequiel Yanka                   -----> ESCRIBIR AQUI")
print("Pogonza, Renzo Lautaro                   -----> ESCRIBIR AQUI")
print("Ponce, Lautaro Nahuel                    -----> ESCRIBIR AQUI")
print("Rojo, Leonardo Daniel                    -----> ESCRIBIR AQUI")
print("Romero Burgos, Elian Emanuel             -----> ESCRIBIR AQUI")
print("Sabin, Iván Ezequiel                     -----> ESCRIBIR AQUI")
print("Solis, Melanie Agustina                  -----> ESCRIBIR AQUI")
print("Sorce, Ramiro Emanuel                    -----> ESCRIBIR AQUI")
print("Toledo, Nicolas                          -----> ESCRIBIR AQUI")
print("Torrilla, Thiago                         -----> ESCRIBIR AQUI")
print("Valenzuela, Luciana                      -----> ESCRIBIR AQUI")
print("Vallejos, Axel                           -----> ESCRIBIR AQUI")
print("Villagra Schimpp, Benjamin Guillermo     -----> ESCRIBIR AQUI")
print("Villalba, Bruno                          -----> ESCRIBIR AQUI")
